version: '3.6'
services:
    service:
      build:
        context: '.'
        dockerfile: Dockerfile
      ports:
          - 4580:80
      volumes:
          - './service:/var/www/html'
          - './run.sh:/run.sh'
          - './.env:/var/www/html/.env'
          - './000-default.conf:/etc/apache2/sites-available/000-default.conf'